language: node_js
cache: 
  directories: 
    - node_modules
    - ~/.npm
node_js: 
  - '12'    
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - fabrizzio1996@gmail.com
    on_success: always
    on_failure: always 
deploy:
  provide: heroku
  skip_cleanup: true
  keep_history: true
  api_key: 93229d11-7495-4c67-a262-af56518d772a
  app: fabz-platzi-store-backend
  on:
    repo: fabz96/platzi-store-backend     